name = "orca-releases"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "73f82799694e2fad048f544e0be28c1c"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "chell-releases"

[[routes]]
pattern = "releases.chell.app/*"
zone_name = "chell.app"
